name: Run the Snyk security scan

on:
  workflow_call:
    secrets:
      token:
        required: true
      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.token }}
          