name: Run the Snyk security scan

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
      
jobs:
  security-scan:
  uses: caravanhealth/.github/workflows/snyk-security-scan.yml@main
  secrets:
    token: ${{ secrets.SNYK_TOKEN }}
          