name: Run the Snyk security scan

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
      
jobs:
  security-scan:
    uses: caravanhealth/github-workflows/.github/workflows/snyk-security-scan.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
