name: Run the Snyk security scan

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
      
jobs:
  security-scan:
    uses: caravanhealth/github-workflows/.github/workflows/snyk-security-scan.yml@main
    with:
      continue-on-error: true
      report-results: ${{ github.event_name != 'pull_request' }}
      code-type: "node"
      cli-args: "--all-projects --severity-threshold=medium"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
